-- =============================================
-- AIMS Aviation Dashboard - Extended Schema
-- Supports: Flights, Swaps, Crew Pairings, Crew Roster (AIMS), Audit Internal
-- =============================================

-- Enable UUID extension if not enabled
create extension if not exists "uuid-ossp";

-- 1. FLIGHTS TABLE
-- Stores flight operations data (Legs)
create table if not exists public.flights (
  flight_id text not null,       -- e.g. VN123
  flight_date date not null,     -- Local Date
  tail_number text not null, 
  ac_type text not null,         -- A321, B787
  std timestamp with time zone not null, -- Scheduled Time Departure (UTC)
  sta timestamp with time zone not null, -- Scheduled Time Arrival (UTC)
  atd timestamp with time zone not null, -- Actual Time Departure (UTC)
  ata timestamp with time zone not null, -- Actual Time Arrival (UTC)
  origin text,
  destination text,
  commercial_ind boolean default true,
  
  /* 
  -- Calculated Fields are moved to View to avoid redundancy and conflict
  -- block_hours numeric(5,2),
  -- delay_minutes integer,
  */
  
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now(),
  
  primary key (flight_id, flight_date)
);

-- 2. AIRCRAFT SWAPS TABLE
-- Tracks planned vs actual aircraft assignments
create table if not exists public.aircraft_swaps (
  swap_id bigint generated by default as identity primary key,
  flight_id text,
  flight_date date,
  planned_tail text,
  actual_tail text,
  swap_reason text,
  swap_timestamp timestamp with time zone default now(),
  
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

-- 3. CREW PAIRINGS TABLE
-- Tracks crew duty assignments (Pairings from AIMS)
create table if not exists public.crew_pairings (
  pairing_id text primary key,    -- Unique Pairing ID from AIMS
  crew_id text,                   -- Employee ID
  duty_start timestamp with time zone,
  duty_end timestamp with time zone,
  deadhead_ind boolean default false,
  flight_id text,                 -- Linked Flight (if applicable)
  base_location text,             -- Base (HAN, SGN)
  
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

-- 4. CREW ROSTER TABLE (NEW - AIMS Integration)
-- Detailed roster activities (SBY, OFF, LEAVE, FLT)
create table if not exists public.crew_roster (
  roster_id bigint generated by default as identity primary key,
  crew_id text not null,
  roster_date date not null,
  duty_code text,                 -- SBY, OFF, AL, FLT
  start_time timestamp with time zone, -- UTC
  end_time timestamp with time zone,   -- UTC
  airport_code text,              -- For SBY/Layover location
  
  -- SBY Specifics
  standby_type text,              -- AM, PM, HOTEL
  
  source_system text default 'AIMS', -- 'AIMS', 'MANUAL'
  
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

-- 5. ETL AUDIT LOG
-- Tracks imports from AIMS Webservice or File Uploads
create table if not exists public.etl_audit_log (
  log_id bigint generated by default as identity primary key,
  job_name text not null,         -- 'IMPORT_FLIGHTS', 'SYNC_AIMS_ROSTER'
  status text not null,           -- 'SUCCESS', 'FAILED', 'RUNNING'
  records_processed integer default 0,
  error_message text,
  started_at timestamp with time zone default now(),
  completed_at timestamp with time zone,
  triggered_by text               -- 'SYSTEM', 'USER:xxx'
);

-- INDEXES
create index if not exists idx_flights_date on public.flights(flight_date);
create index if not exists idx_flights_tail on public.flights(tail_number);
create index if not exists idx_crew_roster_date on public.crew_roster(roster_date);
create index if not exists idx_crew_roster_crew on public.crew_roster(crew_id);

-- ROW LEVEL SECURITY
alter table public.flights enable row level security;
alter table public.aircraft_swaps enable row level security;
alter table public.crew_pairings enable row level security;
alter table public.crew_roster enable row level security;
alter table public.etl_audit_log enable row level security;

-- Default Policies (adjust as needed)
create policy "Public Read" on public.flights for select using (true);
create policy "Public Read" on public.aircraft_swaps for select using (true);
create policy "Public Read" on public.crew_pairings for select using (true);
create policy "Public Read" on public.crew_roster for select using (true);
create policy "Public Read" on public.etl_audit_log for select using (true);
-- Service Role Write
create policy "Service Role Write" on public.flights for insert with check (auth.role() = 'service_role');
-- (Add similar write policies for other tables if using service_role for ETL)

-- VIEWS

-- Metric: Crew Standby Count by Date
create or replace view public.view_crew_standby_metrics as
select
  roster_date,
  airport_code,
  count(*) filter (where duty_code = 'SBY') as sby_count,
  count(*) filter (where duty_code = 'SL') as sick_count
from public.crew_roster
group by roster_date, airport_code;

-- Metric: Flight Metrics (Block Hours & Delays)
create or replace view public.view_flights_metrics as
select
  *,
  (extract(epoch from (ata - atd)) / 3600)::numeric(5,2) as block_hours,
  greatest(0, extract(epoch from (atd - std)) / 60)::integer as delay_minutes
from public.flights;
