-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- Flights Table
create table public.flights (
  flight_id text not null,
  flight_date date not null,
  tail_number text not null,
  ac_type text not null,
  std timestamp with time zone not null,
  sta timestamp with time zone not null,
  atd timestamp with time zone not null,
  ata timestamp with time zone not null,
  origin text,
  destination text,
  commercial_ind boolean default true,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now(),
  primary key (flight_id, flight_date)
);

-- Aircraft Swaps Table
create table public.aircraft_swaps (
  swap_id bigint generated by default as identity primary key,
  flight_id text,
  flight_date date,
  planned_tail text,
  actual_tail text,
  swap_reason text,
  swap_timestamp timestamp with time zone default now(),
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

-- Crew Pairings Table
create table public.crew_pairings (
  pairing_id text primary key,
  crew_id text,
  duty_start timestamp with time zone,
  duty_end timestamp with time zone,
  deadhead_ind boolean default false,
  flight_id text,
  base_location text,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

-- Indexes
create index idx_flights_date on public.flights(flight_date);
create index idx_flights_tail on public.flights(tail_number);
create index idx_flights_commercial on public.flights(flight_date, commercial_ind);

-- View for Calculated Metrics (Block Hours & Delay Minutes)
create or replace view public.view_flights_metrics as
select
  *,
  -- Block Hours: (ATA - ATD) in hours
  (extract(epoch from (ata - atd)) / 3600)::numeric(5,2) as block_hours,
  -- Delay Minutes: (ATD - STD) in minutes, max 0
  greatest(0, extract(epoch from (atd - std)) / 60)::integer as delay_minutes
from public.flights;

-- Storage Bucket Setup (Run this in Supabase Dashboard or SQL Editor)
insert into storage.buckets (id, name, public) 
values ('raw-files', 'raw-files', false)
on conflict (id) do nothing;

-- RLS Policies (Basic secure defaults, adjust as needed)
alter table public.flights enable row level security;
alter table public.aircraft_swaps enable row level security;
alter table public.crew_pairings enable row level security;

create policy "Enable read access for authenticated users" on public.flights for select using (auth.role() = 'authenticated');
create policy "Enable insert for service role only" on public.flights for insert with check (auth.role() = 'service_role');

-- Repeat similar policies for other tables
